apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nameOverride }}-config
  namespace: {{ .Values.namespace }}
data:
    {{- range $key, $value := .Values.config }}
    {{ $key }}: {{ $value | quote }} // toYaml대신 이렇게 사용하는 이유는 문자열로 변환 가능하기 때문에
    {{- end }}