{{- if .Values.autoscaling.enabled }}
{{- if .Values.autoscaling.authentication.enabled }}
apiVersion: keda.sh/v1alpha1
kind: {{ .Values.autoscaling.authentication.kind }}
metadata:
  name: {{ .Values.autoscaling.authentication.name }}
  labels:
    {{- include "flight.labels" . | nindent 4 }}
spec:
  podIdentity:
    {{- toYaml .Values.autoscaling.authentication.podIdentity | nindent 4 }}
---
{{- end }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "flight.hpaName" . }}
  namespace: {{ include "flight.namespace" . }}
  labels:
    {{- include "flight.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "flight.deploymentName" . }}
  pollingInterval: {{ .Values.autoscaling.pollingInterval }}
  cooldownPeriod: {{ .Values.autoscaling.cooldownPeriod }}
  minReplicaCount: {{ .Values.autoscaling.minReplicaCount }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicaCount }}
  triggers:
    {{- toYaml .Values.autoscaling.triggers | nindent 4 }}
{{- end }}
