apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    Environment: prod
    Team: Indiana-Zones
---
apiVersion: v1
kind: Namespace
metadata:
  name: karpenter
  labels:
    Environment: prod
    Team: Indiana-Zones
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    Environment: prod
    Team: Indiana-Zones
---
apiVersion: v1
kind : Namespace
metadata:
  name: airline-payment
  labels:
    Environment: prod
    Team: Indiana-Zones
---
apiVersion: v1
kind: Namespace
metadata:
  name: airline-flight
  labels:
    Environment: prod
    Team: Indiana-Zones
---
apiVersion: v1
kind: Namespace
metadata:
  name: airline-auth
  labels:
    Environment: prod
    Team: Indiana-Zones
