apiVersion: v1
kind: ConfigMap
metadata:
  name: svc-auth-config
  namespace: svc-auth
data:
  SERVER_PORT: "8081"
  SPRING_PROFILES_ACTIVE: "prod"

  DB_HOST: "proxy-1773710218895-rds-airline-mysql-main.proxy-cb8q4mm6485z.ap-northeast-2.rds.amazonaws.com"
  DB_PORT: "3306"

  LOG_LEVEL: "INFO"
