apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: airline-auth
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: "169.254.170.23/32"
    spec:
      serviceAccountName: auth-sa
      containers:
        - name: auth
          image: 036333380579.dkr.ecr.ap-northeast-2.amazonaws.com/airline-backend/auth:latest
          ports:
            - containerPort: 3000       
          envFrom:
            - secretRef:
                name: auth-secret
          env:
            - name: DB_IAM_AUTH
              value: "true"
            # - name: DB_SSL_CA_PATH
            #   value: "/app/certs/global-bundle.pem"
            - name: AWS_STS_REGIONAL_ENDPOINTS
              value: regional
            # - name: AWS_CONTAINER_CREDENTIALS_FULL_URI
            #   value: http://169.254.170.23/v1/credentials
            # - name: AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE
            #   value: /var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
