apiVersion: v1
kind: Service
metadata:
  name: svc-auth
  namespace: airline-auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP