apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 0 # 처음엔 0으로 시작
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            requests:
              cpu: 1 # 포드 하나당 CPU 1개를 점유하게 하여 자리를 부족하게 만듦


# kubectl scale deployment inflate --replicas=5