apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight
  namespace: airline-flight
  labels:
    app: flight
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight
  template:
    metadata:
      labels:
        app: flight
    spec:
      serviceAccountName: flight-sa
      containers:
        - name: flight
          image: 036333380579.dkr.ecr.ap-northeast-2.amazonaws.com/airline-backend/flights:latest
          envFrom:
            - secretRef:
                name: flight-secret
          ports:
            - containerPort: 3000
          env:
            - name: DB_IAM_AUTH
              value: "true"
            - name: DB_SSL_CA_PATH
              value: "/app/certs/global-bundle.pem"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
