apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airline-flight
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: flight=036333380579.dkr.ecr.ap-northeast-2.amazonaws.com/airline-backend/flights
    argocd-image-updater.argoproj.io/flight.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/flight.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/flight.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:/values.yaml
spec:
  project: default
  source:
    repoURL: https://github.com/Megazone-Final/airline-eks.git
    targetRevision: mlee0323/eks/fix
    path: services/flight
    helm:
      releaseName: flight
  destination:
    server: https://kubernetes.default.svc
    namespace: airline-flight
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
