#
# flight-service raw manifest 기준 기본값
#
namespace: airline-flight
appName: flight

deployment:
  name: flight

container:
  name: flight
  port: 3000

replicaCount: 2

image:
  repository: 036333380579.dkr.ecr.ap-northeast-2.amazonaws.com/airline-backend/flight
  pullPolicy: Always
  tag: latest

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: flight-sa

podAnnotations:
  traffic.sidecar.istio.io/excludeOutboundIPRanges: "169.254.170.23/32"

service:
  name: svc-flight
  type: ClusterIP
  port: 3000
  targetPort: 3000

envFrom:
  - secretRef:
      name: flight-secret

externalSecret:
  enabled: true
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  targetName: flight-secret
  remoteKey: airline/service/prod

env:
  - name: DB_IAM_AUTH
    value: "true"
  - name: DB_CONNECTION_LIMIT
    value: "20"
  - name: DB_USER
    value: flight_user
  - name: DB_NAME
    value: flight

resources:
  # 기존 flight-service 요청/제한값 유지
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /livez
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /readyz
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: true
  name: flight-rps
  pollingInterval: 15
  cooldownPeriod: 120
  minReplicaCount: 2
  maxReplicaCount: 500
  authentication:
    enabled: true
    name: keda-aws-auth
    kind: ClusterTriggerAuthentication
    podIdentity:
      provider: aws
  triggers:
    - type: prometheus
      authenticationRef:
        name: keda-aws-auth
        kind: ClusterTriggerAuthentication
      metadata:
        serverAddress: https://aps-workspaces.ap-northeast-2.amazonaws.com/workspaces/ws-c159037a-fe58-47cd-ae91-3ceee618b3b1
        awsRegion: ap-northeast-2
        identityOwner: operator
        metricName: flight_rps
        threshold: "70"
        query: |
          sum(
            rate(
              http_requests_total{
                service="flight",
                route!~"/health|/readyz|/livez"
              }[1m]
            )
          )
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
